### ISSUE TITLE
Update to AdmintLTE 3.2

### ISSUE THREAD

**Issue by hosler** [app-generator/django-adminlte#11]
Can AdminLTE be updated to 3.2? The current version in this project does not include the dark theme.

**Comment by app-generator** [comment]
Hello @hosler 

This evolution is scheduled for an update. 
Probably not all pages will be available but the latest AdminLTE UI Version will be provided.

**Comment by app-generator** [comment]
Hello @hosler 

The `v1.0.7` provides the latest version of AdminLTE `v3.2.0`. 

The product now provides:
- clean codebase, 
- theme-able UI (no more UI hardcoding) 
- CI/CD support via Render

I think we can close this.
