### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by JaumeOS** [app-generator/django-adminlte#14]
https://docs.appseed.us/boilerplate-code/django-templates/adminlte/

![image](https://user-images.githubusercontent.com/77398566/217816413-26a2cbe4-bbed-4acf-a8dc-381127f6f6e9.png)

Here i had to comment the 'django.contrib.admin', line to do the migrations

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
