### ISSUE TITLE
Fontawesome v6 icons not working with replaced source file

### ISSUE THREAD

**Issue by ryanmwleong** [app-generator/django-adminlte#8]
Following the link here, https://fontawesome.com/v6/docs/web/setup/host-yourself/webfonts, I have downloaded the v6 files.
Thereafter, i replaced the entire files into my project under `apps/static/assets/plugins`
However, the fontawesome 6 icons doesn't seem to be working after updating my html template.

**Comment by app-generator** [comment]
Hello @ryanmwleong 

Please use the latest version of the product and let us know if the issue is still there. 

For support, feel free to access: 
https://appseed.us/support/
